version: "2"

linters:
  default: none
  enable:
    - serviceprovider_linter

  settings:
    custom:
      serviceprovider_linter:
        type: module
        description: Enforces open control plane service provider conventions.
        original-url: https://github.com/AndresNico/sp-linter